build:
  environment:
    node: '8.9.4'
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    tests:
      override:
        - command : 'npm test'
          coverage:
            file  : 'coverage/clover.xml'
            format: 'clover'

checks:
  javascript:
    code_rating: true
