build:
  environment:
    node: '8.9.4'
  tests:
    override:
      - command: 'npm test'
        coverage:
          file: 'coverage/clover.xml'
          format: 'clover'
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run

checks:
  javascript:
    code_rating: true
